id: A79CA896C
base_file: fC929.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:05:33.342629
  last_modified_at: 2022-06-19 18:05:33.342636
