id: A79CA896C
base_file: fA4C4.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:05:33.339130
  last_modified_at: 2022-06-19 18:05:33.339137
