id: A79CA896C
base_file: f6A66.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:05:33.333965
  last_modified_at: 2022-06-19 18:05:33.333972
