id: A79CA896C
base_file: f9C4D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:05:33.336582
  last_modified_at: 2022-06-19 18:05:33.336585
