id: A79CA896C
base_file: fD143.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:05:33.344302
  last_modified_at: 2022-06-19 18:05:33.344306
