id: A79CA896C
base_file: fD9DC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-19 18:05:33.347459
  last_modified_at: 2022-06-19 18:05:33.347466
